config/routes.rb
Rails.application.routes.draw do
devise_for :users
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to:"home#top"
get "/home/about" => "home#about", as: "about"
resources :users, only: [:show, :edit,:update,:index]
resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
belongs_to :user

 validates :title, presence: true
 validates :body, length: { maximum: 200 },presence: true
end

app/models/post_image.rb
class PostImage < ApplicationRecord
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          has_many :books, dependent: :destroy
  has_one_attached :profile_image

 validates :name,length: { minimum: 2, maximum: 20 },uniqueness: true
 validates :introduction,length: { maximum: 50 }

 def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
   profile_image.variant(resize_to_limit: [width, height]).processed
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!, except: [:top,:about]
 before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

 def after_sign_out_path_for(resource)
    root_path
 end

 def create
    @user=User.new(user_params)
    @user.save
     flash[:notice] = "Signed out successfully."
    redirect_to root_path(user.id)
 end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @books=Book.new
  end

  def create
    @user=current_user
    @books=Book.all
    @book=Book.new(book_params)
    @book.user_id = current_user.id
    if@book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def index
    @book=Book.new
    @books=Book.all
    @user=current_user
    @book.user_id=@user.id
  end

  def show
    @newbook=Book.new
    @book=Book.find(params[:id])
    @user=@book.user
    @books=@user.books
  end

  def edit
    @book=Book.find(params[:id])
    @user=current_user
   if @book.user_id != current_user.id
    redirect_to books_path
   end
  end

  def update
   @book=Book.find(params[:id])
   if @book.update(book_params)
   flash[:notice] = "You have updated book successfully."
   redirect_to book_path(@book)
   else
     render :edit
   end
  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def get_profile_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end

private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def top
  end

  def about
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new
   
  end

  def create
   
  end

  def index
  end

  def show
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @book=Book.new
    @user=User.find(params[:id])
    @books=@user.books
    @users=current_user
  end

  def edit
    @user=User.find(params[:id])
   if @user.id != current_user.id
    redirect_to user_path(current_user.id)
   end
  end

  def update
    @user=User.find(params[:id])
    @user.update(user_params)
    if@user.save
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user)
    else
    render :edit
    end
  end

  def index
    @users=User.all
    @user=current_user
    @book=Book.new
  end

  def create
    @user=User.new(user_params)
   if @user_log_in.save
    flash[:notice] ="Signed in successfully."
    redirect_to user_path(user.id)
   end
   if @user_sign_in.save
    flash[:notice] ="Welcome! You have signed up successfully."
    redirect_to user_path(user.id)
   end
  end

  def get_profile_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/postimages_helper.rb
module PostimagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
<%= form_with model: @book do |f| %>
  <label for="book_title">Title</label>
  <p><%= f.text_field :title %></p>
  <br>
  <label for="book_body">Opinion</label>
  <p><%= f.text_area :body %></p>
  <br><%= f.submit "Update Book" %>
<% end %>

<p><%= link_to 'Show',book_path(@book.id) %> | <%= link_to 'Back',"/books" %></p>

app/views/books/index.html.erb
<% if @book.errors.any? %>
<h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
 <ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
 </ul>
<% end %>
<%= render 'users/user', book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
<h3>Books</h3>
 <table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
   <tr>
     <td><%= link_to user_path(book.user_id) do %><%= image_tag book.user.get_profile_image(100,100) %><% end %></td>
     <td><%= link_to book_path(book.id) do %><p><%= book.title %></p><% end %></td>
     <td><%=book.body %></td>
   </tr>
  <% end %>
   </tbody>
 </table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-3">
     <h3>User info</h3>
  <%=  image_tag @user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
   <tr>
    <th>name</th><th><%= @user.name %></th>
   </tr>
   <tr>
    <th>introduction</th><th><%= @user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
<p><%= link_to edit_user_path(@user.id),class:"btn btn-outline-secondary btn-block" do%></p>
<i class="fas fa-user-cog"></i>
<% end %>
</div>
<h2>New book</h2>
<%= form_with model: @newbook do |f| %>
  <h6>Title</h6>
    <%= f.text_field :title %>
  <h6>Opinion</h6>
    <%= f.text_area :body %>
  <br><%= f.submit 'Create Book' %>
<% end %>
</div>s
<div class="col-md-8 offset-md-1">
  <h3>Book detail</h3>
  <table class="table">
   <tbody>
    <tr>
     <td><%=image_tag @user.profile_image %>
     <br><%= link_to @user.name,user_path(@user.id) %></td>
     <td><%= link_to @book.title,book_path(@book.id) %></td>
     <td><%=@book.body %></td>
     <% if @book.user == current_user %>
     <td><%= link_to 'Edit',edit_book_path(@book.id)%></td>
     <td><%= link_to 'Destroy',book_path, method: :delete, "data-confirm" => "本当に消しますか？" %></td>
   <% end %>
   </tr>
   </tbody>
  </table>
</div>
</div>
</div>

app/views/home/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
<h1 class="px-3 mx-auto">Welcom to<i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/home/top.html.erb
<div>
  <%= flash[:notice] %>
</div>
<p id="notice"></p>
<div class="container">
 <div class="row">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
<h1>welcom to <i class="fas fa-book"></i>Bookers !!</h1>
<br>In<i class="fas fa-book"></i>Bookers,
<br>you can share and exchange your opinions , inpressions , and emotions
<br>about various books
 <div class="btn-wrapper col-10 mx-auto">
  <div class="row">
 <%= link_to 'Log in',user_session_path,class: "btn btn-info btn-sm btn-block mb-3 log_in" %>
  </div>
  <div class="row">
 <%= link_to 'Sign up',new_user_registration_path,class: "btn btn-success btn-sm btn-block sign_up" %>
  </div>
 </div>
</div>
</div>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice] %>
</div>
<p id="notice"></p>
<div class="container">
 <div class="row">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
<h1>welcom to <i class="fas fa-book"></i>Bookers !!</h1>
<br>In<i class="fas fa-book"></i>Bookers,
<br>you can share and exchange your opinions , inpressions , and emotions
<br>about various books
 <div class="btn-wrapper col-10 mx-auto">
  <div class="row">
 <%= link_to 'Log in',new_user_session_path,class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
  </div>
  <div class="row">
 <%= link_to 'sign_in',new_user_registration_path,class: "btn btn-success btn-sm btn-block sign_up" %>
  </div>
 </div>
</div>
</div>

app/views/layouts/application.html.erb
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body class="d-flex flex-column vh-100">
 <header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <div class="container">
     <%= link_to 'Bookers',root_path %>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNavDropdown">
  <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
     <li>
      <%= link_to user_path(current_user.id) do %>
      <i class="fas fa-home"></i>Home
      <% end %>
     </li>
     <li>
      <%= link_to users_path do %>
      <i class="fas fa-users"></i>Users
      <% end %>
     </li>
     <li>
      <%= link_to books_path do %>
      <i class="fas fa-book-open"></i>Books
      <% end %>
     </li>
    <li class="nav-item">
      <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="fas fa-sign-out-alt"></i>Log out
      <% end %>
    </li>
    <% else %>
    <li>
      <%= link_to root_path do %>
      <i class="fas fa-home"></i>Home
      <% end %>
    </li>
    <li>
      <%= link_to about_path do %>
      <i class="fas fa-link"></i>About
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to new_user_registration_path do %>
      <i class="fas fa-user-plus"></i>Sign up
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to new_user_session_path do %>
      <i class="fas fa-sign-in-alt"></i>Log in
      <% end %>
    </li>
    <% end %>
  </ul>
</div>
      </div>
      </nav>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
      <p>CopyRight Infratop.inc</p>
      </div>
      </div>
      </div>
    </footer>
  </body>

app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>
 

app/views/users/_user.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
<h3>User info</h3>
  <%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
   <tr>
    <th>name</th><th><%= user.name %></th>
   </tr>
   <tr>
    <th>introduction</th><th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
<p><%= link_to edit_user_path(user),class:"btn btn-outline-secondary btn-block" do %></p>
<i class="fas fa-user-cog"></i>
<% end %>
</div>
<h2>New book</h2>
<%= form_with model: book do |f| %>
 <h6>Title</h6>
    <%= f.text_field :title,class: "form-control book_title"%>
  <h6>Opinion</h6>
    <%= f.text_area :body,class: "form-control book_body" %>
  <br><%= f.submit 'Create Book' %>
<% end %>
  </div>

app/views/users/edit.html.erb
<h2>User info</h2>
<% if @user.errors.any? %>
  <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
<%= form_with model: @user do |f| %>
  <label for="user_Name">Name</label>
  <p><%= f.text_field :name%></p>
  <br>
  <label for="user_Image">Image</label>
  <p><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></p>
  <label for="user_Introduction">Introduction</label>
  <p><%= f.text_area :introduction %></p>
  <br><%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<%= render 'user', book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
<h3>Users</h3>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
    </tr>
  </thead>
<tbody>
  <% @users.each do |user| %>
   <tr>
     <td><%=image_tag @user.profile_image %></td>
     <td><%=user.name %></td>
     <td><%= link_to 'Show', user_path(user.id)%></td>
   </tr>
 <% end %>
</tbody>
 </table>
</div>
</div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
     <h3>User info</h3>
  <%=  image_tag @user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
   <tr>
    <th>name</th><th><%= @user.name %></th>
   </tr>
   <tr>
    <th>introduction</th><th><%= @user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to edit_user_path(@user.id),class:"btn btn-outline-secondary btn-block" do %>
   <i class="fas fa-user-cog"></i>
  <% end %>
</div>
<h2>New book</h2>
<%= form_with model: @book do |f| %>
  <h6>Title</h6>
    <%= f.text_field :title,class: "form-control book_title"%>
  <h6>Opinion</h6>
    <%= f.text_area :body,class: "form-control book_body" %>
  <br><%= f.submit 'Create Book' %>
<% end %>
</div>
<div class="col-md-8 offset-md-1">
  <h3>Books</h3>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
 <tbody>
  <% @books.each do |book| %>
   <tr>
    <td><%= link_to user_path(book.user_id) do %><%= image_tag book.user.get_profile_image(100,100) %><% end %></td>
     <td><%= link_to book.title,book_path(book.id) %></td>
     <td><%=book.body %></td>
   </tr>
 <% end %>
   </tbody>
 </table>
</div>
</div>
</div>